---
- name: install nginx
  yum: name=nginx state=present

- name: ensure Apache server is stopped
  service: name=httpd state=stopped enabled=no
  ignore_errors: yes

- name: unneeded Apache RPMs removed
  yum: pkg={{item}} state=absent
  with_items:
    - httpd-tools
    - httpd

# NB Ansible 1.8 doesn't have immediate
#- name: configure firewall
#  firewalld: zone=dmz service={{item}} state=enabled
#             immediate=true permanent=true 
#  with_items:
#    - http
#    - https

- name: configure firewall http
  command: firewall-cmd --zone=dmz --add-service=http
- command: firewall-cmd --zone=dmz --add-service=http --permanent

- name: nginx top level config
  template: src=nginx.top-level-conf.j2 dest=/etc/nginx/nginx.conf backup=no
  notify: restart nginx

- name: no default site
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: restart nginx

- name: nginx site configs
  template: src={{item}}.j2 dest=/etc/nginx/conf.d/{{item}} backup=no
  with_items:
  - myhostname-www.conf
  notify: restart nginx

- name: myonlineuser user is created
  user: name=myonlineuser password="*"

- name: myonlineuser home directory is accessible
  file: path=/home/myonlineuser mode=0701

- name: your public ssh key is authorized
  authorized_key: user=myonlineuser key="{{ lookup('file', '/home/mylocaluser/.ssh/id_rsa.pub') }}"

- name: ensure Nginx server is started
  service: name=nginx state=started enabled=yes



